### ISSUE TITLE
Sending multiple Hystrix command data in zabbix (Like Turbine does)

### ISSUE THREAD

**Issue by mukteshkrmishra** [ahus1/hystrix-examples#4]
Can we send multiple hystrix stream data to zabbix (like turbine does ie: aggregates multiple stream data and show them in dashboard).

**Comment by ahus1** [comment]
As far as I know zabbix will always associate the statistics with one host. I've read that some people created aggregate by creating a dummy host in Zabbix, but I haven't tried that before.

http://sirlagz.net/2015/06/02/calculating-average-availability-of-a-group-of-hosts-in-zabbix/
